export const GET_USER_WALLET_REQUEST = "GET_USER_WALLET_REQUEST";
export const GET_USER_WALLET_SUCCESS = "GET_USER_WALLET_SUCCESS";
export const GET_USER_WALLET_FAILURE = "GET_USER_WALLET_FAILURE";
export const RESET_WALLET_STATE = 'RESET_WALLET_STATE';
