export const FIND_COLLECTION_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_COLLECTION_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const FIND_COLLECTION_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';

export const FIND_COLLECTIONS_REQUEST = 'FIND_COLLECTIONS_REQUEST';
export const FIND_COLLECTIONS_SUCCESS = 'FIND_COLLECTIONS_SUCCESS';
export const FIND_COLLECTIONS_FAILURE = 'FIND_COLLECTIONS_FAILURE';
