export const GET_USER_COUPONS_REQUEST = 'GET_USER_COUPONS_REQUEST'; 
export const GET_USER_COUPONS_SUCCESS = 'GET_USER_COUPONS_SUCCESS';
export const GET_USER_COUPONS_FAILURE = 'GET_USER_COUPONS_FAILURE';
export const RESET_COUPON_STATE = 'RESET_COUPON_STATE';