export const FETCH_JOURNALS_REQUEST = 'FETCH_JOURNALS_REQUEST';
export const FETCH_JOURNALS_SUCCESS = 'FETCH_JOURNALS_SUCCESS';
export const FETCH_JOURNALS_FAILURE = 'FETCH_JOURNALS_FAILURE';

export const FETCH_JOURNAL_REQUEST = 'FETCH_JOURNAL_REQUEST';
export const FETCH_JOURNAL_SUCCESS = 'FETCH_JOURNAL_SUCCESS';
export const FETCH_JOURNAL_FAILURE = 'FETCH_JOURNAL_FAILURE';

export const CREATE_JOURNAL_REQUEST = 'CREATE_JOURNAL_REQUEST';
export const CREATE_JOURNAL_SUCCESS = 'CREATE_JOURNAL_SUCCESS';
export const CREATE_JOURNAL_FAILURE = 'CREATE_JOURNAL_FAILURE';

export const EDIT_JOURNAL_REQUEST = 'EDIT_JOURNAL_REQUEST';
export const EDIT_JOURNAL_SUCCESS = 'EDIT_JOURNAL_SUCCESS';
export const EDIT_JOURNAL_FAILURE = 'EDIT_JOURNAL_FAILURE';

export const DELETE_JOURNAL_REQUEST = 'DELETE_JOURNAL_REQUEST';
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS';
export const DELETE_JOURNAL_FAILURE = 'DELETE_JOURNAL_FAILURE';

export const UPDATE_JOURNAL_SUCCESS = 'UPDATE_JOURNAL_SUCCESS';
export const UPDATE_JOURNAL_FAILURE = 'UPDATE_JOURNAL_FAILURE';
export const UPDATE_JOURNAL_REQUEST = 'UPDATE_JOURNAL_REQUEST';
